name: 离线包制作
on:
  workflow_dispatch:

jobs:
  build:
    name: 离线包制作
    runs-on: ubuntu-22.04
    if: ${{ github.event.repository.owner.id }} == ${{ github.event.sender.id }}

    steps:    
    - name: 准备结束
      uses: actions/checkout@v4

    - name: 创建归档文件
      run: |
        chmod -R +x ${GITHUB_WORKSPACE}/makeself
        ${GITHUB_WORKSPACE}/makeself/makeself.sh ${GITHUB_WORKSPACE}/cs.run "cs script" ${GITHUB_WORKSPACE}/cs.sh

    - name: 上传根文件夹
      uses: actions/upload-artifact@main
      with:
        name: ipk-cs
        path: ${{ github.workspace }}
