name: 离线包制作
on:
  workflow_dispatch:

jobs:
  build:
    name: 离线包制作
    runs-on: ubuntu-22.04
    if: ${{ github.event.repository.owner.id }} == ${{ github.event.sender.id }}

    steps:    
      - name: 准备结束
      uses: actions/checkout@v4
      